branches:
  except:
    - dev
version: '{build}'
platform:
  - x64
image: Visual Studio 2019
build_script:
  - bash -c 'unzip HG-U133_Plus_2.probe_fasta.zip'
  - ps: Invoke-WebRequest ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/gencode.v35.transcripts.fa.gz -OutFile "gencode.v35.transcripts.fa.gz"
  - bash -c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  - bash -c 'gzip -d gencode.v35.transcripts.fa.gz'
  - bash -c './seqmap.exe 0 HG-U133_Plus_2.probe_fasta gencode.v35.transcripts.fa results.txt /eland:3 /available_memory:300000 /output_all_matches'
  - ps: $env:BUILD_NAME="seqmap-$env:APPVEYOR_REPO_TAG_NAME-win-$env:PLATFORM"
  - bash -c 'mkdir $BUILD_NAME'
  - bash -c 'cp seqmap.exe results.txt $BUILD_NAME'
  - bash -c '7z a $BUILD_NAME.zip $BUILD_NAME'
artifacts:
  - path: $(BUILD_NAME).zip
deploy:
  - provider: GitHub
    auth_token:
      secure: u5MrI/3BCylTlSEF21VCYOZ6JMkPpnVhWqFmpqZXXAcczVozk+CNheTOOjL7juo+
    artifact: $(BUILD_NAME).zip
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
