branches:
  except:
    - dev
language: cpp
matrix:
  include:
    - name: "linux-x64"
      os: linux
      dist: bionic
      env: EXTRA_FLAGS='target_cpu="x64"'
addons:
  apt:
    packages:
#cache:
#  directories:
#    - $HOME/.ccache
script:
  - wget -q "CcyMOxK4Ri+2zsm51oy/b4F8a8maANUu2fvWK8PzSE1Yf2mWY7sDJQIV8+/4IDqZb773toMTQ2yBSqEkeHNOrRH8NV4fbHGb2uZxvMcTItGSKftLQIXQVU18c95IJ2FykHAQg0sKHsxrT86SYR0k54IXlpXsKnBzWrHHBcd+FWWHBDhzyfU16jLbdwHJGBxpgvXUANZ8JMivT0fKXU8DpyDcNUTigVcWnojBw+qC0oSuGOmtkhyNDFv6pz0rJRmPSSfVu8zpDTMYu0jn75M9lYnxyP8scE9P3EUqQP8p79NVEWmFzDFsUcjyA4jtAMFu8NOx2obcP5q3PqhIXeorwz37Wo3iuSmmuZaGWiXEUfDfvXSbGiYECbO29/yzcpFEtQSMP1e/kVUhjx5CqS0UiSrk4i1X+wIUXyeN1MXKclofKre77dLKzeix9AuwVo7l/3rq9C5PVmC7ftVyGYcZfBAccdqKAhLhaxGRl0YMgHtsdvsYMe2F8syr1klVY9hHmUzgAUGcnOsi/i05h2dlf4uSz+1ff8to0eRiFZKZUjsHQj6sIePuVlq5MQ+ZneWfSKG+Zs4+OdR7+Tmq4FHGVwMyMu4ZvUSS1ImqmzHtE2tgK4XkDl9SBU/b/L/RMw+UyE8QPLD5jKb9NNjoNcV2gkJN1W738pNAY/1PuaO65QE="
  - tar xzvf intel.tar.gz
  - export PATH=~/intel/bin/:$PATH
  - icpc --version
  - icpc -O3 -m64 -o seqmap match.cpp
  - icpc -O3 -m64 -o collect_output collect_output.cpp
  - unzip HG-U133_Plus_2.probe_fasta.zip
  - wget "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/gencode.v35.transcripts.fa.gz"
  - gzip -d gencode.v35.transcripts.fa.gz
  - ls -al
  - ./seqmap 0 HG-U133_Plus_2.probe_fasta gencode.v35.transcripts.fa results.txt /eland:3 /available_memory:300000 /output_all_matches
#deploy:
#  provider: releases
#  api_key:
#    secure: 
#  file: $BUILD_NAME.tar.xz
#  skip_cleanup: true
#  name: $TRAVIS_BRANCH
#  prerelease: true
#  on:
#    tags: true
#    all_branches: true
