branches:
  except:
  - dev
  - /[0-9].+[0-9]_MSVC+[0-9]*/
  - /[0-9].+[0-9]_OSX/
  - 1.0.13
  - /^untagged/
arch: amd64
os: linux
dist: bionic
addons:
  apt:
    packages:
script:
  - wget "${ICCDL}" -q
  - tar xzf intel.tar.gz
  - export PATH=/home/travis/build/MitsuhaMiyamizu/SeqMap/intel/bin/:$PATH
  - export INTEL_LICENSE_FILE=/home/travis/build/MitsuhaMiyamizu/SeqMap/intel/
  - export CC="icc"
  - export CXX="icpc"
  - icpc --version
  - icpc -O3 -m64 -o seqmap match.cpp
  - icpc -O3 -m64 -o collect_output collect_output.cpp
  - unzip HG-U133_Plus_2.probe_fasta.zip
  - wget "${REF_GENOME}" -q
  - gzip -d gencode.v35.transcripts.fa.gz
  - ./seqmap 0 HG-U133_Plus_2.probe_fasta gencode.v35.transcripts.fa results.txt /eland:3 /available_memory:3000 /output_all_matches
  - mkdir bin_release
  - mv collect_output seqmap results.txt bin_release/
  - zip -r icc_release.zip bin_release/
deploy:
  provider: releases
  token: ${api_key}
  skip_cleanup: true
  file: icc_release.zip
  overwrite: true
  on:
    #tags: true
    all_branches: true
    repo: MitsuhaMiyamizu/SeqMap
