# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- powershell: (new-object System.Net.WebClient).DownloadFile('ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/gencode.v35.transcripts.fa.gz','gencode.v35.transcripts.fa.gz')
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
    cl /EHsc match.cpp /link /out:seqmap.exe
    cl /EHsc collect_output.cpp /link
    dir
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'HG-U133_Plus_2.probe_fasta.zip'
    destinationFolder: '.'
    cleanDestinationFolder: false
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'gencode.v35.transcripts.fa.gz'
    destinationFolder: '.'
    cleanDestinationFolder: false
- script: |
    dir $(Build.ArtifactStagingDirectory)
    .\seqmap.exe 0 HG-U133_Plus_2.probe_fasta gencode.v35.transcripts.fa results.txt /eland:3 /available_memory:300000 /output_all_matches
    mkdir .\bin
    cp seqmap.exe .\bin\
    cp results.txt .\bin\
    cp collect_output.exe .\bin\
  displayName: 'Run a multi-line script'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './bin'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: './$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
- task: GithubRelease@0
  displayName: 'Create GitHub Release'
  inputs:
    gitHubConnection: pushbinary
    repositoryName: MitsuhaMiyamizu/SeqMap
    tagSource: manual
    tag: $(Build.BuildNumber)_MSVC17
    assets: |
      ./$(Build.BuildId).zip
