# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    make
    g++ -O3 -m64 -o collect_output collect_output.cpp
    unzip HG-U133_Plus_2.probe_fasta.zip
    wget "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/gencode.v35.transcripts.fa.gz"
    gzip -d gencode.v35.transcripts.fa.gz
    ls -al
    ./seqmap 0 HG-U133_Plus_2.probe_fasta gencode.v35.transcripts.fa results.txt /eland:3 /available_memory:300000 /output_all_matches
    mkdir bin
    mv collect_output ./bin/
    mv seqmap ./bin/
    mv results.txt ./bin/
  displayName: 'Run a multi-line script'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './bin/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: './$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true

- task: GithubRelease@0
  displayName: 'Create GitHub Release'
  inputs:
    gitHubConnection: pushbinary
    repositoryName: MitsuhaMiyamizu/SeqMap
    tagSource: manual
    tag: $(Build.BuildNumber)_osx
    assets: |
      ./$(Build.BuildId).zip
