name: seqmap
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: unzip
      run: unzip seqmap-1.0.13-src.zip && cd seqmap-1.0.13-src
    - name: make
      run: g++ -O3 -m64 -o seqmap match.cpp
    - name: check binary
      run: ./seqmap --version
