name: seqmap
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: cd /home/runner/work/SeqMap/SeqMap/ && make
    - name: where am I
      run: pwd
    - name: prepare probe fasta 
      run: unzip HG-U133_Plus_2.probe_fasta.zip
    - name: prepare reference genome
      run: wget "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/gencode.v35.transcripts.fa.gz"
    - name: uncompress reference genome
      run: gzip -d gencode.v35.transcripts.fa.gz
    - name: for debug, what files do we have here.
      run: ls -al
    - name: check binary
      run: /home/runner/work/SeqMap/SeqMap/seqmap 0 HG-U133_Plus_2.probe_fasta gencode.v35.transcripts.fa results.txt /eland:3 /available_memory:300000 /output_all_matches
